export const CarsTypes = {
  GET_CARS_REQUEST: "GET_CARS_REQUEST",
  GET_CARS_SUCCESS: "GET_CARS_SUCCESS",
  GET_CARS_FAIL: "GET_CARS_FAIL",
  CREATE_CAR_REQUEST: "CREATE_CAR_REQUEST",
  CREATE_CAR_SUCCESS: "CREATE_CAR_SUCCESS",
  CREATE_CAR_ERROR: "CREATE_CAR_ERROR",
  REMOVE_CAR_REQUEST: "REMOVE_CAR_REQUEST",
  REMOVE_CAR_SUCCESS: "REMOVE_CAR_SUCCESS",
  REMOVE_CAR_ERROR: "REMOVE_CAR_ERROR",
  EDIT_CAR_REQUEST: "EDIT_CAR_REQUEST",
  EDIT_CAR_SUCCESS: "EDIT_CAR_SUCCESS",
  EDIT_CAR_ERROR: "EDIT_CAR_ERROR",
};
